name: antarasa
version: 1.0.0+1
publish_to: none
description: Antarasa Project.
environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  build_runner: ^2.4.12
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_profile_picture: ^2.0.0
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  material_floating_search_bar_2: ^0.5.0
  string_capitalize: ^0.0.10
  supabase_flutter: ^2.6.0
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Light.ttf
          weight: 500
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 400
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 300
        - asset: assets/fonts/Inter-Italic.ttf
# Backend Password : antarasabackend123
